import React from 'react';

export const aimlQuizzes = [
  {
    id: 101,
    title: 'Introduction to AI - Easy',
    unit: 'Unit I',
    difficulty: 'Easy',
    time: '15 min',
    questions: 20,
    xp: 50,
    status: 'Completed',
    score: '85%',
    questionData: [
      {
        id: 1,
        question: 'Which of the following is NOT one of the four classical AI approaches?',
        options: ['Acting humanly', 'Thinking humanly', 'Acting emotionally', 'Acting rationally'],
        correct: 2,
        explanation: 'The four approaches are Acting Humanly, Thinking Humanly, Thinking Rationally, and Acting Rationally.',
        topics: ['What is AI?'],
      },
      {
        id: 2,
        question: 'Which capability is essential to pass the Turing Test?',
        options: ['A. Robotics', 'B. Natural Language Processing', 'C. Image Processing', 'D. Networking'],
        correct: 1,
        explanation: 'NLP allows machines to communicate in human language.',
        topics: ['What is AI?'],
      },
      {
        id: 3,
        question: 'A computer passes the Turing Test if a human interrogator cannot ______ between the computer and a human.',
        options: ['A. communicate', 'B. interact', 'C. distinguish', 'D. analyze'],
        correct: 2,
        explanation: 'The test checks if machine responses are indistinguishable from human responses.',
        topics: ['What is AI?'],
      },
      {
        id: 4,
        question: 'The Laws of Thought approach is based on:',
        options: ['Psychology', 'Logic', 'Biology', 'Sociology'],
        correct: 1,
        explanation: 'It uses formal logic to derive correct conclusions.',
        topics: ['What is AI?'],
      },
      {
        id: 5,
        question: 'A rational system is one that makes the ______ choice given its knowledge.',
        options: ['fastest', 'cheapest', 'right', 'random'],
        correct: 2,
        explanation: 'Rationality means choosing the action that maximizes expected performance.',
        topics: ['Rationality'],
      },
      {
        id: 6,
        question: 'A rational agent always tries to:',
        options: ['Behave like humans', 'Act randomly', 'Achieve the best expected outcome', 'Follow rules blindly'],
        correct: 2,
        explanation: 'Rational agents maximize expected performance.',
        topics: ['Rationality'],
      },
      {
        id: 7,
        question: 'An agent perceives its environment using:',
        options: ['Actuators', 'Sensors', 'Motors', 'Programs'],
        correct: 1,
        explanation: 'Sensors gather environmental information.',
        topics: ['Intelligent Agents'],
      },
      {
        id: 8,
        question: 'The complete history of percepts is called a ______ sequence.',
        options: ['Action', 'Sensor', 'State', 'Percept'],
        correct: 3,
        explanation: 'Percept sequence records all past perceptions.',
        topics: ['Intelligent Agents'],
      },
      {
        id: 9,
        question: 'A human agent uses ______ as sensors and ______ as actuators.',
        options: ['hands, legs',
          'eyes and ears, hands and legs',
          'brain, heart',
          'keyboard, mouse'],
        correct: 1,
        explanation: 'Eyes and ears perceive the environment; hands and legs act on it.',
        topics: ['Intelligent Agents'],
      },
      {
        id: 10,
        question: 'PEAS stands for:',
        options: ['Performance, Environment, Actuators, Sensors',
          'Program, Execution, Agent, System',
          'Percept, Environment, Action, State',
          'Planning, Execution, Analysis, Search'],
        correct: 0,
        explanation: 'PEAS defines task environments.',
        topics: ['Task Environments'],
      },
      {
        id: 11,
        question: 'An environment where actions affect future decisions is called:',
        options: ['Episodic',
          'Sequential',
          'Single-agent',
          'Deterministic'],
        correct: 1,
        explanation: 'In sequential environments, current actions influence future states.',
        topics: ['Task Environments'],
      },
      {
        id: 12,
        question: 'Which environment changes while the agent is deciding?',
        options: ['Static',
          'Deterministic',
          'Dynamic',
          'Episodic'],
        correct: 2,
        explanation: 'In dynamic environments, the world evolves as the agent acts (e.g., traffic).',
        topics: ['Task Environments'],
      },
      {
        id: 13,
        question: 'Which agent improves its behavior using feedback from the environment?',
        options: ['Simple reflex',
          'Goal-based',
          'Utility-based',
          'Learning agent'],
        correct: 3,
        explanation: 'Learning agents adapt and improve over time.',
        topics: ['The Structure of agents'],
      },
      {
        id: 14,
        question: 'Simple reflex agents select actions based only on the ______ percept.',
        options: ['A. previous',
          'B. current',
          'C. future',
          'D. complete'],
        correct: 1,
        explanation: 'They ignore percept history and memory.',
        topics: ['The Structure of agents'],
      },
      {
        id: 15,
        question: 'Which agent type is best suited for handling changing goals?',
        options: ['Simple reflex agent', 'Model-based agent', 'Goal-based agent', 'Reflex agent'],
        correct: 2,
        explanation: 'Goal-based agents can adapt by redefining goals without rewriting rules.',
        topics: ['The Structure of agents'],
      },
      {
        id: 16,
        question: 'The first step in problem solving is:',
        options: ['A. Search', 'B. Execution', 'C. Goal formulation', 'D. Path cost'],
        correct: 2,
        explanation: 'Goal formulation defines what the agent wants.',
        topics: ['Problem-solving'],
      },
      {
        id: 17,
        question: 'Breadth-First Search uses which data structure?',
        options: ['A. Stack', 'B. Queue', 'C. Array', 'D. Tree'],
        correct: 1,
        explanation: 'Breadth-First Search uses a queue to explore nodes level by level.',
        topics: ['Problem-solving','BFS'],
      },
      {
        id: 18,
        question: 'Depth-First Search uses which data structure?',
        options: ['A. Stack', 'B. Queue', 'C. Array', 'D. Tree'],
        correct: 0,
        explanation: 'Depth-First Search uses a stack to explore nodes.',
        topics: ['Problem-solving','DFS'],
      },
      {
        id: 19,
        question: 'IDDFS combines the advantages of ______ and ______.',
        options: ['A. BFS and DFS',
                  'B. DFS and UCS',
                  'C. A* and BFS',
                  'D. UCS and DFS'],
        correct: 1,
        explanation: 'IDDFS is memory efficient like DFS and complete like BFS.',
        topics: ['Problem-solving','IDDFS'],
      },
      {
        id: 20,
        question: 'Depth-First Search may fail due to:',
        options: ['High memory usage',
                  'Infinite loops',
                  'High cost',
                  'Queue overflow'],
        correct: 1,
        explanation: 'DFS can get stuck in deep or infinite paths.',
        topics: ['Problem-solving','DFS'],
      },
      // Add more questions...
    ]
  },
  {
    id: 102,
    title: 'Introduction to AI - Medium',
    unit: 'Unit I',
    difficulty: 'Medium',
    time: '25 min',
    questions: 10,
    xp: 100,
    status: 'Available',
    score: '-',
    questionData: [
      {
        id: 1,
        question: 'Assertion (A): The rational agent approach evaluates intelligence based on achieving the best expected outcome rather than imitating human behavior.Reason (R): Rational agents focus on maximizing a performance measure using mathematics and engineering principles.',
        options: ['Both A and R are true, and R correctly explains A',
                  'Both A and R are true, but R does not explain A',
                  'A is true, but R is false',
                  'A is false, but R is true'],
        correct: 0,
        explanation: 'The rational agent approach defines intelligence in terms of optimal action selection.Its foundation in mathematics and engineering directly explains this outcome-oriented evaluation.',
        topics: ['Rationality'],
      },
      {
        id: 2,
        question: 'Assertion (A): Fully observable environments eliminate the need for internal state representation.\nReason (R): In sequential environments, history influences future decisions even with full observability.',
        options: ['Both A and R are true, and R correctly explains A',
                  'Both A and R are true, but R does not explain A',
                  'A is true, but R is false',
                  'A is false, but R is true'],
        correct: 3,
        explanation: 'Full observability alone does not remove the need for memory.Sequential dependency requires tracking past states.',
        topics: ['Task Environments'],
      },
      {
        id: 3,
        question: 'Assertion (A): A task environment can be known even if it is partially observable.\nReason (R): Knowing the rules and action outcomes does not imply full visibility of the current state.',
        options: ['Both A and R are true, and R correctly explains A',
                  'Both A and R are true, but R does not explain A',
                  'A is true, but R is false',
                  'A is false, but R is true'],
        correct: 0,
        explanation: 'Chess rules are fully known even when some information may be hidden.Knowledge refers to rules, not percept completeness.',
        topics: ['Task Environments'],
      },
      {
        id: 4,
        question: 'Assertion (A): Simple reflex agents perform poorly in partially observable environments.\nReason (R): They ignore percept history and rely only on the current percept.',
        options: ['Both A and R are true, and R correctly explains A',
                  'Both A and R are true, but R does not explain A',
                  'A is true, but R is false',
                  'A is false, but R is true'],
        correct: 0,
        explanation: 'Without memory, the agent cannot infer hidden state information.This leads to looping or incorrect actions.',
        topics: ['Structure of Agents'],
      },
      {
        id: 5,
        question: 'Assertion (A): The Turing Test provides a complete definition of intelligence.Reason (R): The test focuses on imitating human responses rather than understanding underlying intelligence mechanisms.',
        options: ['Both A and R are true, and R correctly explains A',
                  'Both A and R are true, but R does not explain A',
                  'A is true, but R is false',
                  'A is false, but R is true'],
        correct: 3,
        explanation: 'The Turing Test does not fully define intelligence.It emphasizes behavior imitation, not internal reasoning or understanding.',
        topics: ['what is AI?'],
      },
      {
        id: 6,
        question: 'Assertion (A):Breadth-first search expands all nodes at a given depth before expanding nodes at the next depth.Reason (R):Breadth-first search uses a LIFO queue to store frontier nodes.',
        options: ['Both A and R are true, and R correctly explains A',
                  'Both A and R are true, but R does not explain A',
                  'A is true, but R is false',
                  'A is false, but R is true'],
        correct: 2,
        explanation: 'Assertion is true.Reason is false because BFS uses a FIFO queue, not LIFO.',
        topics: ['DFS'],
      },
      {
        id: 7,
        question: 'Assertion (A):Breadth-first search is optimal in all problem environments.Reason (R):Breadth-first search always expands the shallowest unexpanded node first.',
        options: ['Both A and R are true, and R correctly explains A',
                  'Both A and R are true, but R does not explain A',
                  'A is true, but R is false',
                  'A is false, but R is true'],
        correct: 3,
        explanation: 'Assertion is false because BFS is optimal only when step costs are equal.\nReason is true.',
        topics: ['BFS'],
      },
      {
        id: 8,
        question: 'Assertion (A):Breadth-first search has low memory requirements compared to depth-first search.\nReason (R):Breadth-first search stores all generated nodes in memory.',
        options: ['Both A and R are true, and R correctly explains A',
                  'Both A and R are true, but R does not explain A',
                  'A is true, but R is false',
                  'A is false, but R is true'],
        correct: 3,
        explanation: 'Assertion is false (BFS needs very high memory).\nReason is true.',
        topics: ['BFS'],
      },
      {
        id: 9,
        question: 'Assertion (A):Depth-limited search is guaranteed to be complete.Reason (R):Depth-limited search may fail if the solution lies beyond the depth limit.',
        options: ['Both A and R are true, and R correctly explains A',
                  'Both A and R are true, but R does not explain A',
                  'A is true, but R is false',
                  'A is false, but R is true'],
        correct: 3,
        explanation: 'Assertion is false.\nReason is true.',
        topics: ['DLS'],
      },
      {
        id: 10,
        question: 'Assertion (A):Iterative deepening search has higher memory requirements than breadth-first search.Reason (R):Iterative deepening search stores only a single path from root to leaf at a time.',
        options: ['Both A and R are true, and R correctly explains A',
                  'Both A and R are true, but R does not explain A',
                  'A is true, but R is false',
                  'A is false, but R is true'],
        correct: 3,
        explanation: 'Assertion is false (IDDFS uses much less memory).Reason is true.',
        topics: ['IDDFS'],
      },
      // Medium level questions for Unit I
    ]
  },
  {
    id: 103,
    title: 'Introduction to AI - Hard',
    unit: 'Unit I',
    difficulty: 'Hard',
    time: '35 min',
    questions: 5,
    xp: 200,
    status: 'Locked',
    score: '-',
    questionData: [
      {
        id: 1,
        question: 'A self-driving taxi strictly follows traffic rules using logical rules but fails badly when unexpected roadblocks appear. Which AI approach is primarily responsible for this limitation?',
        options: ['Acting humanly', 'Thinking humanly', 'Thinking rationally', 'Acting rationally'],
        correct: 2,
        explanation: 'The thinking rationally (laws of thought) approach relies on strict logical inference rules.Real-world environments like traffic are uncertain, dynamic, and computationally complex.Pure logic struggles to handle incomplete information and unpredictable events.',
        topics: ['What is AI?'],
      },
      {
        id: 2,
        question: 'A home-assistant robot keeps colliding with furniture when lights are off, even though it has perfect movement rules. What is the most appropriate improvement?',
        options: ['Convert it to a simple reflex agent',
                  'Add a learning element to update behavior',
                  'Replace sensors with faster actuators',
                  'Remove internal state representation'],
        correct: 1,
        explanation: 'The problem arises due to changing environmental conditions.A learning element allows the agent to adapt based on experience.This improves performance without rewriting rules manually.',
        topics: ['Intelligent Agents'],
      },
      {
        id: 3,
        question: 'A robot vacuum does not know the room layout initially and spends time exploring before cleaning efficiently. Which agent ability enables this behavior?',
        options: ['Goal testing',
                  'Exploration',
                  'Utility maximization',
                  'Logical inference'],
        correct: 1,
        explanation: 'Exploration allows the agent to gather useful information.This improves future decision-making.It is essential when the environment is initially unknown.',
        topics: ['Intelligent Agents'],
      },
      {
        id: 4,
        question: 'A robot in a warehouse changes its route when a path becomes blocked mid-task. Which property does this environment exhibit?',
        options: ['Episodic',
                  'Static',
                  'Deterministic',
                  'Dynamic'],
        correct: 3,
        explanation: 'The environment changes while the agent is acting.Such changes require real-time adaptation.This characterizes a dynamic environment.',
        topics: ['Task Environments'],
      },
      {
        id: 5,
        question: 'A delivery robot ignores road width and traffic lights while planning routes but still reaches the destination correctly. Which problem-solving principle is applied?',
        options: ['A. Goal testing',
                  'B. Abstraction',
                  'C. Utility maximization',
                  'D. State expansion'],
        correct: 1,
        explanation: 'The robot removes irrelevant details to simplify planning.Only information affecting reachability is retained.This reduces complexity while preserving solution correctness.',
        topics: ['Task Environments'],
      },
      // Hard level questions for Unit I
    ]
  },
  {
    id: 201,
    title: 'Search Strategies - Easy',
    unit: 'Unit II',
    difficulty: 'Easy',
    time: '20 min',
    questions: 12,
    xp: 60,
    status: 'Available',
    score: '-',
    questionData: [
      // Easy questions for Unit II
    ]
  },
  // Add more quizzes for other units...
];

export default aimlQuizzes;
